# Generated by Django 5.1.3 on 2024-11-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('NO', 'None'), ('WF', 'Walk Forward'), ('WB', 'Walk Back'), ('WR', 'Walk Right'), ('WL', 'Walk Left'), ('JP', 'Jump Once'), ('JM', 'Jump Multiple Times'), ('SK', 'Shake Sideways'), ('SU', 'Shake Upwards'), ('SP', 'Spin')], default='NO', max_length=30)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('distance', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
