# Generated by Django 5.1.3 on 2024-11-30 18:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_characters', '0003_location_quest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('title', models.CharField(max_length=250)),
                ('condition', models.TextField(default='')),
                ('description', models.TextField()),
                ('creation', models.TimeField(auto_now_add=True)),
                ('is_quest', models.BooleanField(default=False)),
                ('is_cutscene', models.BooleanField(default=False)),
                ('quest_step', models.PositiveIntegerField(default=0)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_characters.location')),
                ('quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_characters.quest')),
            ],
        ),
    ]
