# Generated by Django 5.1.3 on 2024-11-30 19:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_characters', '0004_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('comment', models.TextField()),
                ('name', models.CharField(max_length=250)),
                ('txt_en', models.TextField()),
                ('txt_pt', models.TextField(blank=True, null=True)),
                ('txt_es', models.TextField(blank=True, null=True)),
                ('portrait', models.CharField(choices=[('DF', 'Default'), ('CT', 'Custom'), ('HP', 'Happy'), ('SD', 'Sad'), ('EX', 'Excited'), ('TD', 'Thoughtful / Thinking'), ('DT', 'Distracted'), ('TN', 'Tense'), ('PN', 'In Pain'), ('CF', 'Confused'), ('DZ', 'Dizzy'), ('CR', 'Crying'), ('TR', 'Teary'), ('IP', 'Inpired /Amazed'), ('SP', 'Surprised'), ('WR', 'Worried')], default='DF', max_length=25)),
                ('is_first', models.BooleanField(default=False)),
                ('has_fork', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_characters.conversation')),
                ('next_speech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='speech_next', to='a_characters.speech')),
                ('previous_speech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='speech_prev', to='a_characters.speech')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_characters.character')),
            ],
        ),
    ]
