# Generated by Django 5.1.3 on 2024-12-01 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_characters', '0005_speech'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='fork_question_en_A',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='fork_question_en_B',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='fork_question_en_C',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='fork_question_en_D',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='fork_question_en_E',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='fork_question_en_F',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='fork_question_es_A',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='fork_question_es_B',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='fork_question_es_C',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='fork_question_es_D',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='fork_question_es_E',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='fork_question_es_F',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='fork_question_pt_A',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='fork_question_pt_B',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='fork_question_pt_C',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='fork_question_pt_D',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='fork_question_pt_E',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='fork_question_pt_F',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='fork_speech_AA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fork_next_speech_A', to='a_characters.speech'),
        ),
        migrations.AddField(
            model_name='speech',
            name='fork_speech_BB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fork_next_speech_B', to='a_characters.speech'),
        ),
        migrations.AddField(
            model_name='speech',
            name='fork_speech_CC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fork_next_speech_C', to='a_characters.speech'),
        ),
        migrations.AddField(
            model_name='speech',
            name='fork_speech_DD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fork_next_speech_D', to='a_characters.speech'),
        ),
        migrations.AddField(
            model_name='speech',
            name='fork_speech_EE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fork_next_speech_E', to='a_characters.speech'),
        ),
        migrations.AddField(
            model_name='speech',
            name='fork_speech_FF',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fork_next_speech_F', to='a_characters.speech'),
        ),
    ]
