# Generated by Django 5.1.3 on 2024-12-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_characters', '0006_speech_fork_question_en_a_speech_fork_question_en_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
