# Generated by Django 5.1.3 on 2024-12-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_characters', '0007_alter_character_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
