# Generated by Django 5.1.3 on 2024-12-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_characters', '0008_character_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='portraits',
            field=models.SmallIntegerField(default=0),
        ),
    ]
