# Generated by Django 5.1.3 on 2024-12-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_characters', '0009_character_portraits'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='indoors',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
