# Generated by Django 5.1.3 on 2025-01-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_characters', '0010_location_indoors_alter_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_linear',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='total_speeches',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quest',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='description_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='number_of_steps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quest',
            name='title_es',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='title_pt',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='fork_letter',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='is_fork',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speech',
            name='line_hash',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='localized_es',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speech',
            name='localized_pt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='speech',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
