# Generated by Django 5.1.3 on 2025-01-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_characters', '0011_conversation_is_linear_conversation_total_speeches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='name_es',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='character',
            name='name_pt',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='speech',
            name='fork_letter',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
