# Generated by Django 5.1.3 on 2025-01-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_characters', '0012_character_name_es_character_name_pt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='broken_chain',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='speech',
            name='fork_letter',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
    ]
