# Generated by Django 5.1.3 on 2025-01-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_characters', '0013_conversation_broken_chain_alter_speech_fork_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='my_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='my_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speech',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
