# Generated by Django 5.1.3 on 2025-01-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_characters', '0014_conversation_my_code_speech_my_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='line_hash',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
