# Generated by Django 5.1.3 on 2025-01-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_characters', '0015_alter_speech_line_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='next_is_cycled',
            field=models.BooleanField(default=False),
        ),
    ]
