# Generated by Django 5.1.3 on 2025-01-15 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_characters', '0016_speech_next_is_cycled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_characters.character'),
        ),
    ]
