# Generated by Django 5.1.3 on 2025-09-06 17:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('NO', 'None'), ('WF', 'Walk Forward'), ('WB', 'Walk Back'), ('WR', 'Walk Right'), ('WL', 'Walk Left'), ('JP', 'Jump Once'), ('JM', 'Jump Multiple Times'), ('SK', 'Shake Sideways'), ('SU', 'Shake Upwards'), ('SP', 'Spin'), ('CF', 'Confused')], default='NO', max_length=30)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('distance', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('name', models.CharField(max_length=250, unique=True)),
                ('name_pt', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('name_es', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('walkable', models.BooleanField(default=False)),
                ('in_game', models.BooleanField(default=False)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
