# Generated by Django 5.1.3 on 2025-09-06 18:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_babel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('name', models.CharField(max_length=250, unique=True)),
                ('name_pt', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('name_es', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('indoors', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=25, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=250, unique=True)),
                ('title_pt', models.CharField(max_length=250, null=True, unique=True)),
                ('title_es', models.CharField(max_length=250, null=True, unique=True)),
                ('description', models.TextField()),
                ('description_pt', models.TextField(null=True)),
                ('description_es', models.TextField(null=True)),
                ('condition', models.TextField()),
                ('number_of_steps', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('title', models.CharField(max_length=250, unique=True)),
                ('condition', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_quest', models.BooleanField(default=False)),
                ('is_cutscene', models.BooleanField(default=False)),
                ('in_game', models.BooleanField(default=False)),
                ('my_code', models.TextField(blank=True, null=True)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('quest_step', models.PositiveIntegerField(default=0)),
                ('is_linear', models.BooleanField(default=True)),
                ('creation', models.TimeField(auto_now_add=True)),
                ('broken_chain', models.BooleanField(default=False)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_babel.location')),
                ('quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_babel.quest')),
            ],
        ),
    ]
