# Generated by Django 5.1.3 on 2025-09-06 20:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_babel', '0002_location_quest_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('is_first', models.BooleanField(default=False)),
                ('has_fork', models.BooleanField(default=False)),
                ('is_fork', models.BooleanField(default=False)),
                ('fork_letter', models.TextField(blank=True, max_length=26)),
                ('next_is_cycled', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('my_code', models.TextField(blank=True, null=True)),
                ('txt_en', models.TextField()),
                ('txt_pt', models.TextField(blank=True, null=True)),
                ('txt_es', models.TextField(blank=True, null=True)),
                ('my_fork_question_en', models.TextField(blank=True, null=True)),
                ('my_fork_question_pt', models.TextField(blank=True, null=True)),
                ('my_fork_question_es', models.TextField(blank=True, null=True)),
                ('localized_pt', models.BooleanField(default=False)),
                ('localized_es', models.BooleanField(default=False)),
                ('portrait', models.CharField(choices=[('DF', 'Default'), ('CT', 'Custom'), ('HP', 'Happy'), ('SD', 'Sad'), ('EX', 'Excited'), ('TD', 'Thoughtful / Thinking'), ('DT', 'Distracted'), ('TN', 'Tense'), ('PN', 'In Pain'), ('CF', 'Confused'), ('DZ', 'Dizzy'), ('CR', 'Crying'), ('TR', 'Teary'), ('IP', 'Inpired /Amazed'), ('SP', 'Surprised'), ('WR', 'Worried')], default='DF', max_length=25)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_babel.conversation')),
                ('next_speech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='speech_next', to='app_babel.speech')),
                ('previous_speech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='speech_prev', to='app_babel.speech')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_babel.character')),
            ],
        ),
    ]
