# Generated by Django 5.1.3 on 2025-09-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_babel', '0003_speech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='condition',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='description_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='title_es',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='title_pt',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
