# Generated by Django 5.1.3 on 2025-09-24 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_babel', '0004_alter_quest_condition_alter_quest_description_es_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speech',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='speech',
            name='fork_letter',
        ),
        migrations.RemoveField(
            model_name='speech',
            name='has_fork',
        ),
        migrations.RemoveField(
            model_name='speech',
            name='is_first',
        ),
        migrations.RemoveField(
            model_name='speech',
            name='is_fork',
        ),
        migrations.RemoveField(
            model_name='speech',
            name='localized_es',
        ),
        migrations.RemoveField(
            model_name='speech',
            name='localized_pt',
        ),
        migrations.RemoveField(
            model_name='speech',
            name='my_code',
        ),
        migrations.RemoveField(
            model_name='speech',
            name='my_fork_question_en',
        ),
        migrations.RemoveField(
            model_name='speech',
            name='my_fork_question_es',
        ),
        migrations.RemoveField(
            model_name='speech',
            name='my_fork_question_pt',
        ),
        migrations.RemoveField(
            model_name='speech',
            name='name',
        ),
        migrations.RemoveField(
            model_name='speech',
            name='next_is_cycled',
        ),
        migrations.RemoveField(
            model_name='speech',
            name='next_speech',
        ),
        migrations.RemoveField(
            model_name='speech',
            name='portrait',
        ),
        migrations.RemoveField(
            model_name='speech',
            name='previous_speech',
        ),
        migrations.RemoveField(
            model_name='speech',
            name='speaker',
        ),
    ]
