# Generated by Django 5.1.3 on 2025-09-24 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_babel', '0005_remove_speech_comment_remove_speech_fork_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='previous_speech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='app_babel.speech'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='speeches', to='app_babel.conversation'),
        ),
    ]
