# Generated by Django 5.1.3 on 2025-09-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_babel', '0006_speech_previous_speech_alter_speech_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
