# Generated by Django 5.1.3 on 2025-09-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_babel', '0007_speech_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
    ]
