# Generated by Django 5.1.3 on 2025-10-04 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_babel', '0009_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='next_is_cycled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speech',
            name='next_speech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merges_back', to='app_babel.speech'),
        ),
    ]
