# Generated by Django 5.1.3 on 2025-10-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_babel', '0010_speech_next_is_cycled_speech_next_speech'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='fq_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='fq_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='fq_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='has_fork',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speech',
            name='is_fork',
            field=models.BooleanField(default=False),
        ),
    ]
