# Generated by Django 5.1.3 on 2025-10-08 19:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_babel', '0011_speech_fq_en_speech_fq_es_speech_fq_pt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conditional',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250, null=True)),
                ('comment', models.CharField(max_length=250, null=True)),
                ('double_else', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conditionals', to='app_babel.conversation')),
            ],
        ),
        migrations.AddField(
            model_name='speech',
            name='conditional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ifs', to='app_babel.conditional'),
        ),
    ]
