# Generated by Django 5.1.3 on 2025-10-08 19:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_babel', '0012_conditional_speech_conditional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=5, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
